[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.11",
    "asyncio>=3.4.3",
    "twscrape>=0.17.0",
]
