name = "reverb-portfolio"
main = "../cloudflare-worker.js"
compatibility_date = "2024-06-01"

# High-availability configuration
[env.production]
workers_dev = false
route = "reverb256.ca/*"

# KV namespace for static asset caching
[[kv_namespaces]]
binding = "STATIC_ASSETS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# Vaultwarden integration for secrets
[vars]
VAULTWARDEN_URL = "https://vault.reverb256.ca"
GITHUB_FALLBACK_URL = "https://reverb256.github.io"